create table dbo.tb_usuarios
(
	nm_login varchar(50) not null,
	nm_usuario varchar(100) not null,
	ds_acesso varchar(50) not null
)

select * from dbo.tb_usuarios

insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_FCH')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_FCH')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_CC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_CC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_CTT')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_D_CTT')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_CTT')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_I_CTT')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_SBU')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_SBU')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_FNC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_FNC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_PRM')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_PRM')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_PSJ')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_PSJ')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_PSA')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_REC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_K_REC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_REC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_EXC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_EXC')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_TRF')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_E_TRF')
insert into dbo.tb_usuarios values ('radm', 'Ricardo Melo', 'LHH_C_REL')


insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_FCH')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_FCH')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_CC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_CC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_CTT')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_D_CTT')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_CTT')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_I_CTT')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_SBU')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_SBU')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_FNC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_FNC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_PRM')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_PRM')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_PSJ')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_PSJ')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_PSA')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_REC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_K_REC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_REC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_EXC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_EXC')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_TRF')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_E_TRF')
insert into dbo.tb_usuarios values ('pgen', 'Priscila Genova', 'LHH_C_REL')